stages:
  train:
    cmd: python train_pipeline.py --config configs/train_config.yaml
    deps:
    - configs/train_config.yaml
    - data
    outs:
    - models/losses.json
    - models/model.pkl
    
