# Input data
input_demand_orders: "data/raw/demand_orders_2023_09_22.csv"
input_demand_orders_status: "data/raw/demand_orders_status_2023_09_22.csv"
input_sales: "data/raw/sales.csv"
input_features: "data/raw/features.csv"
# Output data
output_sku_demand_day: "data/processed/sku_demand_day.csv"
output_features_and_targets: "data/processed/features_targets.csv"
output_losses: "models/losses.json"
output_model: "models/model.pkl"
output_predictions: data/processed/predictions.csv
# Parameters
feature_params:
  sku_demand_day:
    - "day"
    - "sku_id"
    - "sku,price"
    - "qty"
  targets:
    next_7d: ["qty", 7]
    next_14d: ["qty", 14]
    next_21d: ["qty", 21]
  features:
    qty_7d_avg: ["qty", 7, "avg", 0]
    qty_7d_q10: ["qty", 7, "quantile", 10]
    qty_7d_q50: ["qty", 7, "quantile", 50]
    qty_7d_q90: ["qty", 7, "quantile", 90]
    qty_14d_avg: ["qty", 14, "avg", 0]
    qty_14d_q10: ["qty", 14, "quantile", 10]
    qty_14d_q50: ["qty", 14, "quantile", 50]
    qty_14d_q90: ["qty", 14, "quantile", 90]
    qty_21d_avg: ["qty", 21, "avg", 0]
    qty_21d_q10: ["qty", 21, "quantile", 10]
    qty_21d_q50: ["qty", 21, "quantile", 50]
    qty_21d_q90: ["qty", 21, "quantile", 90]
split_params:
  test_days: 30
model_params:
  features:
    ["price",
    "qty",
    "qty_7d_avg",
    "qty_7d_q10",
    "qty_7d_q50",
    "qty_7d_q90",
    "qty_14d_avg",
    "qty_14d_q10",
    "qty_14d_q50",
    "qty_14d_q90",
    "qty_21d_avg",
    "qty_21d_q10",
    "qty_21d_q50",
    "qty_21d_q90",
    ]
  horizons: [7, 14, 21]
  quantiles: [0.1, 0.5, 0.9]
